version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: kalyan
      MYSQL_USER: kalyan
      MYSQL_PASSWORD: 1234
    volumes:
      - ./mydb.sql:/docker-entrypoint-initdb.d/mydb.sql
